#!/usr/bin/bash
iptables -X
iptables -F
iptables -I INPUT -d 192.168.1.0/24 -j NFQUEUE --queue-num 1
iptables -I OUTPUT -s 192.168.1.0/24 -j NFQUEUE --queue-num 2
iptables -I FORWARD -j NFQUEUE --queue-num 3
